name: Run M3u Generator
on:
  schedule:
    - cron: "0 */2 * * *"  # Her 2 saatte bir Ã§alÄ±ÅŸacak ÅŸekilde ayarlandÄ±
  workflow_dispatch:  # Elle Ã§alÄ±ÅŸtÄ±rmaya izin verir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Depoyu Klonla
        uses: actions/checkout@v3

      - name: ğŸ Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Gerekli BaÄŸÄ±mlÄ±lÄ±klarÄ± Kur
        run: pip install -r requirements.txt || echo "No dependencies found."

      - name: ğŸš€ M3U DosyasÄ±nÄ± OluÅŸtur
        run: python txt_to_m3u.py

      - name: âœ… DeÄŸiÅŸiklikleri Kontrol Et ve Commit Yap
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"

          # DeÄŸiÅŸiklikleri kontrol et
          if git status --porcelain | grep .; then
            echo "DeÄŸiÅŸiklikler tespit edildi, commit atÄ±lÄ±yor..."
            git add output.m3u  # GÃ¼ncellenen dosyayÄ± ekleyin.
            git commit -m "M3U dosyasÄ± hazÄ±r. Ä°yi seyirler ğŸ˜Š"
            git push origin HEAD:main
          else
            echo "DeÄŸiÅŸiklik yok, commit atÄ±lmayacak."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token ile yetkilendirme yap
